export const authConstant = {
    LOGIN__REQUEST: 'LOGIN__REQUEST',
    LOGIN__FAILUE: 'LOGIN__FAILUE',
    LOGOUT__SUCCESS: 'LOGOUT__SUCCESS',
    LOGIN__SUCCESS: 'LOGIN__SUCCESS',
};
export const urlConstant = {
    URL__ACTION: 'URL__ACTION',
    URL__UPDATEPRICE: 'URL__UPDATEPRICE',
    URL__REMOVEPRiVE: 'URL__REMOVE',
    URL__UPDATESORT: 'URL__UPDATESORT',
    URL__REMOVEPRICE: 'URL__REMOVEPRICE',
    URL__UPDATECREATEAT: 'URL__UPDATECREATEAT',
};
