export const authConstant = {
    LOGIN__REQUEST: 'LOGIN__REQUEST',
    LOGIN__FAILUE: 'LOGIN__FAILUE',
    LOGOUT__SUCCESS: 'LOGOUT__SUCCESS',
    LOGIN__SUCCESS: 'LOGIN__SUCCESS',
};
export const urlConstant = {
    URL__UPDATEPRICE: 'URL__UPDATEPRICE',
    URL__UPDATESORT: 'URL__UPDATESORT',
    URL__UPDATECREATEAT: 'URL__UPDATECREATEAT',
    URL__CLIENTCHOOSE: 'URL__CLIENTCHOOSE',
    URL__DELETECHOOSECHECKBOX: 'URL__DELETECHOOSECHECKBOX',
    URL__DELETECHOOSECOLOR: 'URL__DELETECHOOSECOLOR',
    URL__UPDATECOLOR: 'URL__UPDATECOLOR',
    URL__DELETECOLOR: 'URL__DELETECOLOR',
    URL__ACTION: 'URL__ACTION',
    URL__DELETECHOOSE: 'URL__DELETECHOOSE',
    URL__REMOVEPRiVE: 'URL__REMOVE',
    URL__REMOVEPRICE: 'URL__REMOVEPRICE',
};
